# Generated by Django 4.2.11 on 2026-09-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('AGENCY', 'Agency')], db_index=True, help_text='Unique identifier code for the plan (e.g. FREE, STARTER, AGENCY).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='User-facing display name for the plan.', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price for the plan (e.g. 0, 1500, 6000).', max_digits=10)),
                ('currency', models.CharField(default='ETB', help_text='Currency code (default ETB).', max_length=10)),
                ('max_projects', models.PositiveIntegerField(default=1, help_text='Maximum allowed websites/projects a user on this plan can track.')),
                ('max_keywords', models.PositiveIntegerField(default=3, help_text='Maximum total keywords across all projects a user on this plan can track.')),
                ('basic_tool_daily_limit', models.PositiveIntegerField(default=5, help_text='Daily execution limit for basic SEO tools. 0 represents unlimited daily usage.')),
                ('features', models.JSONField(default=list, help_text='List of FeatureCode strings entitled for users on this plan.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active and available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'subscriptions_plan',
                'ordering': ['monthly_price', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(db_index=True, help_text='Identifier code of the tool (e.g. meta_generator, sitemap_validator).', max_length=100)),
                ('usage_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Calendar date of usage (UTC/local date).')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of times the tool was invoked on this date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who performed the tool action.', on_delete=django.db.models.deletion.CASCADE, related_name='tool_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tool usage',
                'verbose_name_plural': 'tool usages',
                'db_table': 'subscriptions_tool_usage',
                'ordering': ['-usage_date', '-count'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', help_text='Current billing/subscription status.', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the subscription period began.')),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Timestamp when the current billing period expires (null for lifetime/free).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='The active plan tier for this user.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.OneToOneField(help_text='The user who owns this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='toolusage',
            constraint=models.UniqueConstraint(fields=('user', 'tool_code', 'usage_date'), name='unique_user_tool_daily_usage'),
        ),
    ]
