# Generated by Django 4.2.11 on 2026-09-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price billed for this transaction.', max_digits=10)),
                ('currency', models.CharField(default='ETB', help_text='Currency code (default ETB).', max_length=10)),
                ('provider', models.CharField(default='doxa', help_text='Payment provider identifier (e.g. doxa).', max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='Transaction identifier assigned by the payment gateway.', max_length=255, null=True)),
                ('checkout_reference', models.CharField(db_index=True, help_text='Unique internal reference used to correlate checkouts, callbacks, and webhooks.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='Current payment lifecycle status.', max_length=20)),
                ('checkout_url', models.TextField(blank=True, default='', help_text='Hosted or provider checkout URL presented to the user.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual payment metadata (customer details, gateway payload).')),
                ('error_message', models.TextField(blank=True, default='', help_text='Reason recorded if payment or verification failed.')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was successfully verified.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='The plan tier being purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='subscriptions.plan')),
                ('subscription', models.ForeignKey(blank=True, help_text='The active subscription record associated with this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='subscriptions.subscription')),
                ('user', models.ForeignKey(help_text='The user who initiated the payment transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'db_table': 'subscriptions_payment_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_19a6e1_idx'), models.Index(fields=['checkout_reference'], name='subscriptio_checkou_639d3b_idx'), models.Index(fields=['provider', 'provider_transaction_id'], name='subscriptio_provide_53020c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('provider', 'provider_transaction_id'), name='unique_provider_transaction_id'),
        ),
    ]
