"""
DoxaRank Specialized SEO Agents Package (Phase 4.7).
"""

from .base_agent import BaseSpecializedAgent, SharedContext, AgentResult
from .agent_handoff import (
    AgentHandoffContext,
    CollaborationState,
    AgentHandoffValidator,
    AgentHandoffValidationError,
    EvidenceItem,
    InferenceItem,
    UncertaintyItem,
    KNOWN_AGENTS,
)
from .shared_memory import (
    SharedWorkingMemory,
    MemoryItem,
    MemoryCategory,
    DecisionStatus,
    CollaborationDecision,
    ConflictStatus,
    MemoryConflict,
    AgentRevisitReason,
    RevisitRecord,
    ContextBudgetConfig,
    SharedMemoryRegistry,
)
from .task_planner import (
    AgentTask,
    TaskPlan,
    TaskStatus,
    TaskPriority,
    ReplanReason,
    DynamicTaskPlanner,
    PlanBudgetConfig,
    TaskPlanRegistry,
    TaskPlanningError,
    CircularDependencyError,
    InvalidTaskTransitionError,
    PlanLimitExceededError,
    PlanBudgetExceededError,
)
from .seo_research_agent import SEOResearchAgent
from .seo_investigation_agent import SEOInvestigationAgent
from .seo_strategy_agent import SEOStrategyAgent
from .seo_action_agent import SEOActionPlanningAgent
from .seo_verification_agent import SEOVerificationAgent
from .parallel_executor import ParallelExecutionBatch, ParallelBatchExecutor, BatchExecutionResult
from .adaptive_selector import (
    AdaptiveAgentSelector, AgentCapabilityProfile, RoutingDecision, WorkloadTracker,
    CandidateScoreBreakdown, RejectedCandidate
)
from .agent_learning import (
    AgentPerformanceRecord, AgentPerformanceStats, HistoricalSignal,
    AgentPerformanceStore, AgentLearningService, FailureCategory,
    get_agent_learning_service
)
from .seo_supervisor import SEOSupervisorAgent, SEOSupervisor, ROUTING_WORKFLOWS
from .advanced_reasoning import (
    ConsensusState,
    ChallengeType,
    CritiqueSeverity,
    DisagreementSeverity,
    ReasoningStatus,
    EpistemicType,
    ReasoningEvidence,
    ReasoningHypothesis,
    AgentReasoningResult,
    AgentCritique,
    DisagreementRecord,
    ReasoningRound,
    ConsensusResult,
    ReasoningCase,
    AdvancedReasoningService,
    ReasoningRegistry,
    MAX_REASONING_ROUNDS,
    CONSENSUS_CONFIDENCE_THRESHOLD,
    PARTIAL_CONSENSUS_THRESHOLD,
    CONSENSUS_MARGIN_THRESHOLD,
)

__all__ = [
    "BaseSpecializedAgent",
    "SharedContext",
    "AgentResult",
    "AgentHandoffContext",
    "CollaborationState",
    "AgentHandoffValidator",
    "AgentHandoffValidationError",
    "EvidenceItem",
    "InferenceItem",
    "UncertaintyItem",
    "KNOWN_AGENTS",
    "SharedWorkingMemory",
    "MemoryItem",
    "MemoryCategory",
    "DecisionStatus",
    "CollaborationDecision",
    "ConflictStatus",
    "MemoryConflict",
    "AgentRevisitReason",
    "RevisitRecord",
    "ContextBudgetConfig",
    "SharedMemoryRegistry",
    "AgentTask",
    "TaskPlan",
    "TaskStatus",
    "TaskPriority",
    "ReplanReason",
    "DynamicTaskPlanner",
    "PlanBudgetConfig",
    "TaskPlanRegistry",
    "TaskPlanningError",
    "CircularDependencyError",
    "InvalidTaskTransitionError",
    "PlanLimitExceededError",
    "PlanBudgetExceededError",
    "ParallelExecutionBatch",
    "ParallelBatchExecutor",
    "BatchExecutionResult",
    "AdaptiveAgentSelector",
    "AgentCapabilityProfile",
    "RoutingDecision",
    "WorkloadTracker",
    "CandidateScoreBreakdown",
    "RejectedCandidate",
    "AgentPerformanceRecord",
    "AgentPerformanceStats",
    "HistoricalSignal",
    "AgentPerformanceStore",
    "AgentLearningService",
    "FailureCategory",
    "get_agent_learning_service",
    "SEOResearchAgent",
    "SEOInvestigationAgent",
    "SEOStrategyAgent",
    "SEOActionPlanningAgent",
    "SEOVerificationAgent",
    "SEOSupervisorAgent",
    "SEOSupervisor",
    "ROUTING_WORKFLOWS",
    "ConsensusState",
    "ChallengeType",
    "CritiqueSeverity",
    "DisagreementSeverity",
    "ReasoningEvidence",
    "ReasoningHypothesis",
    "AgentReasoningResult",
    "AgentCritique",
    "DisagreementRecord",
    "ReasoningRound",
    "ConsensusResult",
    "ReasoningCase",
    "AdvancedReasoningService",
    "ReasoningRegistry",
    "MAX_REASONING_ROUNDS",
    "CONSENSUS_CONFIDENCE_THRESHOLD",
    "PARTIAL_CONSENSUS_THRESHOLD",
    "CONSENSUS_MARGIN_THRESHOLD",
]
