# Generated by Django 4.2.11 on 2026-09-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], default='google', help_text='Third-party identity or service provider.', max_length=50)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('expired', 'Expired'), ('error', 'Error')], default='connected', help_text='Current operational status of this integration.', max_length=30)),
                ('account_email', models.CharField(blank=True, help_text='Email address of the connected third-party account.', max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Display name of the connected third-party account.', max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, help_text='Unique identifier (e.g. Google subject ID) from provider.', max_length=255, null=True)),
                ('encrypted_access_token', models.TextField(blank=True, help_text='Encrypted OAuth2 access token.', null=True)),
                ('encrypted_refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth2 refresh token.', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp of the active access token.', null=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='List of granted OAuth scopes.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata and settings.')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the connection was initially established.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last token refresh or connection update.')),
                ('user', models.ForeignKey(help_text='The DoxaRank user who owns this provider connection.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Connection',
                'verbose_name_plural': 'Integration Connections',
                'db_table': 'integrations_connections',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='int_user_provider_idx'), models.Index(fields=['provider', 'status'], name='int_provider_status_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
