# Generated by Django 4.2.11 on 2026-09-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGA4Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(help_text='The GA4 property ID (e.g. "123456789").', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the GA4 property.', max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, help_text='The Google Analytics account ID.', max_length=100, null=True)),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this project is actively connected to GA4.')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the GA4 property was associated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update.')),
                ('project', models.OneToOneField(help_text='The project linked to this GA4 property.', on_delete=django.db.models.deletion.CASCADE, related_name='ga4_connection', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project GA4 Connection',
                'verbose_name_plural': 'Project GA4 Connections',
                'db_table': 'integrations_ga4_connections',
                'ordering': ['-connected_at'],
            },
        ),
    ]
