# Generated by Django 4.2.11 on 2026-09-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('integrations', '0002_projectga4connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClarityConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_project_id', models.CharField(help_text='The Microsoft Clarity project/site ID (e.g. "k9xyz123").', max_length=100)),
                ('name', models.CharField(blank=True, help_text='Display name of the Clarity project.', max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, help_text='Website URL configured in Clarity.', max_length=500, null=True)),
                ('encrypted_api_token', models.TextField(blank=True, help_text='Encrypted Clarity Data Export API token if configured.', null=True)),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this project is actively connected to Microsoft Clarity.')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the Clarity project was associated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update.')),
                ('project', models.OneToOneField(help_text='The project linked to this Microsoft Clarity project.', on_delete=django.db.models.deletion.CASCADE, related_name='clarity_connection', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Clarity Connection',
                'verbose_name_plural': 'Project Clarity Connections',
                'db_table': 'integrations_clarity_connections',
                'ordering': ['-connected_at'],
            },
        ),
    ]
