# Generated by Django 4.2.11 on 2026-09-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('integrations', '0003_projectclarityconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGTMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='The GTM account ID (e.g. "123456").', max_length=100)),
                ('container_id', models.CharField(help_text='The GTM container ID (numeric ID, e.g. "789012").', max_length=100)),
                ('container_public_id', models.CharField(help_text='The public GTM container ID (e.g. "GTM-XXXXXX").', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Display name of the GTM container.', max_length=255, null=True)),
                ('usage_context', models.JSONField(blank=True, default=list, help_text='GTM usage contexts (e.g. ["web"]).')),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this project is actively connected to GTM.')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the GTM container was associated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update.')),
                ('project', models.OneToOneField(help_text='The project linked to this GTM container.', on_delete=django.db.models.deletion.CASCADE, related_name='gtm_connection', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project GTM Connection',
                'verbose_name_plural': 'Project GTM Connections',
                'db_table': 'integrations_gtm_connections',
                'ordering': ['-connected_at'],
            },
        ),
    ]
