# Generated by Django 4.2.11 on 2026-08-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='The search query to track (e.g. "seo agency ethiopia").', max_length=255)),
                ('search_engine', models.CharField(choices=[('google', 'Google')], default='google', help_text='Target search engine.', max_length=50)),
                ('country', models.CharField(choices=[('ET', 'Ethiopia')], default='ET', help_text='Target country code (e.g. "ET" for Ethiopia).', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', help_text='Target search language code (e.g. "en", "am").', max_length=10)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', help_text='Target device type (desktop or mobile).', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether rank tracking is active for this keyword.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The project/website this keyword belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='projects.project')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'db_table': 'seo_keywords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('project', 'keyword', 'search_engine', 'country', 'language', 'device'), name='unique_keyword_configuration_per_project'),
        ),
    ]
