# Generated by Django 4.2.11 on 2026-08-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Observed ranking position in search results (e.g. 1 for rank #1).')),
                ('ranking_url', models.URLField(blank=True, help_text='The exact landing page URL found ranking on the search engine.', max_length=500, null=True)),
                ('search_engine', models.CharField(choices=[('google', 'Google')], default='google', help_text='Target search engine.', max_length=50)),
                ('country', models.CharField(choices=[('ET', 'Ethiopia')], default='ET', help_text='Target country code.', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', help_text='Target search language code.', max_length=10)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', help_text='Target device type.', max_length=20)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp when the ranking observation occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(help_text='The tracked keyword this ranking observation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='seo.keyword')),
            ],
            options={
                'verbose_name': 'keyword ranking',
                'verbose_name_plural': 'keyword rankings',
                'db_table': 'seo_keyword_rankings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='keywordranking',
            constraint=models.UniqueConstraint(fields=('keyword', 'search_engine', 'country', 'language', 'device', 'recorded_at'), name='unique_ranking_observation_per_time'),
        ),
    ]
