# Generated by Django 4.2.11 on 2026-08-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0002_keywordranking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current status of the audit job.', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Overall SEO health score from 0 to 100.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the audit execution began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the audit execution concluded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the audit was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the audit was last updated.')),
                ('error_message', models.TextField(blank=True, help_text='Error details if the audit failed.', null=True)),
                ('project', models.ForeignKey(help_text='The project/website this site audit belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='projects.project')),
            ],
            options={
                'verbose_name': 'site audit',
                'verbose_name_plural': 'site audits',
                'db_table': 'seo_site_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(db_index=True, help_text='Category identifier of the issue (e.g. missing_title, slow_load, 404_link).', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('notice', 'Notice')], db_index=True, default='warning', help_text='Severity level of the issue.', max_length=20)),
                ('title', models.CharField(help_text='Short summary title of the issue.', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of what was found.')),
                ('page_url', models.URLField(blank=True, help_text='URL of the affected page if applicable.', max_length=500, null=True)),
                ('recommendation', models.TextField(blank=True, help_text='Recommended action steps to resolve the issue.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the issue record was created.')),
                ('audit', models.ForeignKey(help_text='The site audit this issue belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo.siteaudit')),
            ],
            options={
                'verbose_name': 'audit issue',
                'verbose_name_plural': 'audit issues',
                'db_table': 'seo_audit_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='siteaudit',
            index=models.Index(fields=['project', '-created_at'], name='seo_site_au_project_bd7594_idx'),
        ),
        migrations.AddIndex(
            model_name='siteaudit',
            index=models.Index(fields=['status'], name='seo_site_au_status_59ac12_idx'),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['audit', '-created_at'], name='seo_audit_i_audit_i_1512b0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['severity'], name='seo_audit_i_severit_7437cc_idx'),
        ),
    ]
