# Generated by Django 4.2.11 on 2026-08-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0003_siteaudit_auditissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_url', models.CharField(help_text='The Search Console site URL or domain property (e.g. "sc-domain:example.com" or "https://example.com/").', max_length=500)),
                ('permission_level', models.CharField(choices=[('siteOwner', 'Site Owner'), ('siteFullUser', 'Full User'), ('siteRestrictedUser', 'Restricted User'), ('siteUnverifiedUser', 'Unverified User')], default='siteOwner', help_text='Permission level of the authenticated user on this Search Console property.', max_length=50)),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this project is actively connected to Google Search Console.')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the Search Console connection was established.')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent data sync from Search Console.', null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed')], default='idle', help_text='Current data synchronization status.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the connection or last sync failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project linked to this Search Console property.', on_delete=django.db.models.deletion.CASCADE, related_name='search_console_connection', to='projects.project')),
            ],
            options={
                'verbose_name': 'Search Console connection',
                'verbose_name_plural': 'Search Console connections',
                'db_table': 'seo_search_console_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_connected'], name='seo_gsc_proj_conn_idx'), models.Index(fields=['sync_status'], name='seo_gsc_sync_status_idx')],
            },
        ),
    ]
