# Generated by Django 4.2.11 on 2026-08-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_searchconsoleconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Observation date for this analytics row.')),
                ('query', models.CharField(blank=True, db_index=True, default='', help_text='Search query / keyword string from Google Search Console.', max_length=500)),
                ('page', models.CharField(blank=True, db_index=True, default='', help_text='Landing page URL from Google Search Console.', max_length=500)),
                ('country', models.CharField(blank=True, default='', help_text='Country code (e.g. "eth", "usa", "ET").', max_length=10)),
                ('device', models.CharField(blank=True, default='', help_text='Device category (e.g. "desktop", "mobile", "tablet").', max_length=20)),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Total number of clicks from organic search results.')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Total number of impressions in organic search results.')),
                ('ctr', models.DecimalField(decimal_places=4, default=0.0, help_text='Click-through rate (e.g. 0.0543 for 5.43% or raw decimal).', max_digits=7)),
                ('position', models.DecimalField(decimal_places=2, default=0.0, help_text='Average ranking position in organic search results.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('connection', models.ForeignKey(help_text='The Search Console connection this analytics record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='search_analytics', to='seo.searchconsoleconnection')),
            ],
            options={
                'verbose_name': 'Search Analytics record',
                'verbose_name_plural': 'Search Analytics data',
                'db_table': 'seo_search_analytics_data',
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['connection', '-date'], name='seo_analytics_conn_date_idx'), models.Index(fields=['connection', 'date'], name='seo_analytics_c_d_asc_idx'), models.Index(fields=['date'], name='seo_analytics_date_idx'), models.Index(fields=['query'], name='seo_analytics_query_idx'), models.Index(fields=['page'], name='seo_analytics_page_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='searchanalyticsdata',
            constraint=models.UniqueConstraint(fields=('connection', 'date', 'query', 'page', 'country', 'device'), name='unique_search_analytics_observation'),
        ),
    ]
