# Generated by Django 4.2.11 on 2026-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_searchanalyticsdata_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchanalyticsdata',
            name='unique_search_analytics_observation',
        ),
        migrations.AddField(
            model_name='searchanalyticsdata',
            name='search_appearance',
            field=models.CharField(blank=True, default='', help_text='Search appearance dimension (e.g. "AMP_ARTICLE", "RICHDATA").', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='searchanalyticsdata',
            constraint=models.UniqueConstraint(fields=('connection', 'date', 'query', 'page', 'country', 'device', 'search_appearance'), name='unique_search_analytics_observation'),
        ),
    ]
