# Generated by Django 4.2.11 on 2026-08-26 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0006_remove_searchanalyticsdata_unique_search_analytics_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Deterministic unique fingerprint for deduplication across analysis runs.', max_length=255)),
                ('insight_type', models.CharField(choices=[('ranking_drop', 'Ranking Drop'), ('ranking_improvement', 'Ranking Improvement'), ('page_two_keyword', 'Page Two Opportunity'), ('high_impressions_low_ctr', 'High Impressions Low CTR'), ('declining_clicks', 'Declining Clicks'), ('declining_impressions', 'Declining Impressions'), ('low_ctr', 'Low CTR'), ('high_position_opportunity', 'High Position Opportunity'), ('technical_seo_issue', 'Technical SEO Issue'), ('keyword_cannibalization', 'Keyword Cannibalization'), ('content_opportunity', 'Content Opportunity')], db_index=True, help_text='Category / rule type of the insight.', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('opportunity', 'Opportunity'), ('info', 'Info')], db_index=True, default='info', help_text='Severity level of the insight.', max_length=20)),
                ('title', models.CharField(help_text='Concise summary of the insight.', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of observed SEO behavior or metric change.')),
                ('recommendation', models.TextField(blank=True, default='', help_text='Actionable recommendation to address or capitalize on this insight.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], db_index=True, default='open', help_text='Workflow status of this insight.', max_length=20)),
                ('source', models.CharField(choices=[('ranking', 'Ranking'), ('search_console', 'Search Console'), ('site_audit', 'Site Audit'), ('combined', 'Combined')], db_index=True, default='ranking', help_text='Data source where this insight was derived from.', max_length=30)),
                ('related_url', models.CharField(blank=True, default='', help_text='Landing page URL associated with this insight.', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured metadata (metrics, comparisons, delta values).')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the insight condition was first or most recently detected.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when this insight was marked resolved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this insight record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this insight record was last updated.')),
                ('project', models.ForeignKey(help_text='The project this SEO insight belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='projects.project')),
                ('related_keyword', models.ForeignKey(blank=True, help_text='Specific keyword tracked in DoxaRank associated with this insight.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='seo.keyword')),
            ],
            options={
                'verbose_name': 'SEO insight',
                'verbose_name_plural': 'SEO insights',
                'db_table': 'seo_insights',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_ins_proj_stat_idx'), models.Index(fields=['project', 'severity'], name='seo_ins_proj_sev_idx'), models.Index(fields=['project', 'insight_type'], name='seo_ins_proj_type_idx'), models.Index(fields=['project', '-detected_at'], name='seo_ins_proj_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seoinsight',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='unique_project_insight_fingerprint'),
        ),
    ]
