# Generated by Django 4.2.11 on 2026-08-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0007_seoinsight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('meta_title', 'Meta Title'), ('meta_description', 'Meta Description'), ('content_update', 'Content Update'), ('keyword_optimization', 'Keyword Optimization'), ('internal_linking', 'Internal Linking'), ('technical_seo', 'Technical SEO'), ('ranking_recovery', 'Ranking Recovery'), ('ctr_optimization', 'CTR Optimization'), ('page_two_opportunity', 'Page Two Opportunity'), ('general_seo', 'General SEO')], db_index=True, default='general_seo', help_text='Type of SEO optimization recommended.', max_length=50)),
                ('title', models.CharField(help_text='Concise title summarizing the recommendation.', max_length=255)),
                ('summary', models.TextField(help_text='High-level summary of the issue and rationale.')),
                ('explanation', models.TextField(help_text='In-depth explanation of the observed SEO evidence and causal factors.')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='high', help_text='Execution priority.', max_length=20)),
                ('recommended_action', models.TextField(help_text='Concrete step-by-step instructions for the user/developer.')),
                ('expected_impact', models.TextField(help_text='Estimated realistic SEO impact without false certainty.')),
                ('affected_url', models.CharField(blank=True, default='', help_text='Target URL for applying the recommendation.', max_length=500)),
                ('affected_keyword', models.CharField(blank=True, default='', help_text='Target keyword query associated with this recommendation.', max_length=255)),
                ('generated_content', models.JSONField(blank=True, default=dict, help_text='Structured copy proposals (e.g. proposed title, meta description, copy outlines).')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], db_index=True, default='pending_review', help_text='Workflow approval status of this recommendation.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the recommendation was generated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the recommendation was last modified.')),
                ('insight', models.ForeignKey(help_text='The originating SEO insight this recommendation addresses.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='seo.seoinsight')),
                ('project', models.ForeignKey(help_text='The project this AI recommendation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project')),
            ],
            options={
                'verbose_name': 'SEO recommendation',
                'verbose_name_plural': 'SEO recommendations',
                'db_table': 'seo_recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_rec_proj_stat_idx'), models.Index(fields=['project', 'priority'], name='seo_rec_proj_prio_idx'), models.Index(fields=['insight', 'status'], name='seo_rec_ins_stat_idx'), models.Index(fields=['project', '-created_at'], name='seo_rec_proj_date_idx')],
            },
        ),
    ]
