# Generated by Django 4.2.11 on 2026-08-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0008_seorecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOContentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Working title for the content brief.', max_length=255)),
                ('target_keyword', models.CharField(blank=True, default='', help_text='Primary target search keyword.', max_length=255)),
                ('secondary_keywords', models.JSONField(blank=True, default=list, help_text='List of supporting / secondary keywords.')),
                ('search_intent', models.CharField(choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('commercial', 'Commercial Investigation'), ('navigational', 'Navigational')], db_index=True, default='informational', help_text='Dominant search intent category.', max_length=50)),
                ('target_url', models.CharField(blank=True, default='', help_text='Target URL / existing URL to optimize or create.', max_length=500)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog / Article'), ('landing_page', 'Landing Page'), ('page_optimization', 'Existing-Page Optimization'), ('technical_implementation', 'Technical SEO Implementation')], db_index=True, default='blog_post', help_text='Type of content asset (blog, landing page, page optimization, technical).', max_length=50)),
                ('recommended_title', models.CharField(blank=True, default='', help_text='Optimized meta / H1 title proposition.', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='Recommended meta description (140-160 characters).')),
                ('suggested_slug', models.CharField(blank=True, default='', help_text='Recommended URL slug hierarchy.', max_length=255)),
                ('content_angle', models.TextField(blank=True, default='', help_text='Unique value proposition, editorial angle, or competitive differentiation.')),
                ('audience', models.CharField(blank=True, default='', help_text='Target reader or buyer persona.', max_length=255)),
                ('outline', models.JSONField(blank=True, default=list, help_text='Structured outline items with heading levels, section titles, and talking points.')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Essential arguments, facts, or concepts that must be included.')),
                ('internal_link_suggestions', models.JSONField(blank=True, default=list, help_text='Recommended internal link targets and anchor texts.')),
                ('external_link_suggestions', models.JSONField(blank=True, default=list, help_text='Authoritative external reference suggestions.')),
                ('faq_questions', models.JSONField(blank=True, default=list, help_text='Frequently asked questions to target SERP features (PPA/FAQ schema).')),
                ('entities_topics', models.JSONField(blank=True, default=list, help_text='Topical entities and semantic concepts to establish topical authority.')),
                ('content_length_target', models.PositiveIntegerField(blank=True, default=1500, help_text='Recommended word count target.', null=True)),
                ('generated_content', models.JSONField(blank=True, default=dict, help_text='Full structured brief JSON as returned by the AI provider.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Workflow status of this brief.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the brief was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the brief was last updated.')),
                ('project', models.ForeignKey(help_text='The project this content brief belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='content_briefs', to='projects.project')),
                ('recommendation', models.ForeignKey(blank=True, help_text='The originating SEO recommendation this brief was synthesized from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_briefs', to='seo.seorecommendation')),
            ],
            options={
                'verbose_name': 'SEO content brief',
                'verbose_name_plural': 'SEO content briefs',
                'db_table': 'seo_content_briefs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_brief_proj_stat_idx'), models.Index(fields=['project', 'content_type'], name='seo_brief_proj_type_idx'), models.Index(fields=['recommendation', 'status'], name='seo_brief_rec_stat_idx'), models.Index(fields=['project', '-created_at'], name='seo_brief_proj_date_idx')],
            },
        ),
    ]
