# Generated by Django 4.2.11 on 2026-08-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0009_seocontentbrief'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Working title for the generated content draft.', max_length=255)),
                ('target_keyword', models.CharField(blank=True, default='', help_text='Primary target search keyword.', max_length=255)),
                ('secondary_keywords', models.JSONField(blank=True, default=list, help_text='List of supporting / secondary keywords incorporated.')),
                ('search_intent', models.CharField(choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('commercial', 'Commercial Investigation'), ('navigational', 'Navigational')], db_index=True, default='informational', help_text='Search intent category targeted by the draft.', max_length=50)),
                ('target_url', models.CharField(blank=True, default='', help_text='Target canonical URL for the draft.', max_length=500)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog / Article'), ('landing_page', 'Landing Page'), ('page_optimization', 'Existing-Page Optimization'), ('technical_implementation', 'Technical SEO Implementation')], db_index=True, default='blog_post', help_text='Content archetype (blog post, landing page, page optimization, technical implementation).', max_length=50)),
                ('introduction', models.TextField(blank=True, default='', help_text='Engaging opening paragraph answering user search intent.')),
                ('content_body', models.TextField(blank=True, default='', help_text='Complete articulated Markdown content body of the draft.')),
                ('outline_structure', models.JSONField(blank=True, default=list, help_text='Structured outline sections with headings, levels, paragraphs, and key points.')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Exact word count of the generated draft.')),
                ('keyword_usage', models.JSONField(blank=True, default=dict, help_text='Deterministic keyword density and occurrences tracking map.')),
                ('internal_links', models.JSONField(blank=True, default=list, help_text='Internal links with anchor texts, URLs, and target section context.')),
                ('external_links', models.JSONField(blank=True, default=list, help_text='Authoritative external reference citations.')),
                ('faq_section', models.JSONField(blank=True, default=list, help_text='List of FAQ items (question and answer) designed for FAQ schema.')),
                ('meta_title', models.CharField(blank=True, default='', help_text='Recommended title tag for search engines.', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='Recommended meta description snippet.')),
                ('suggested_slug', models.CharField(blank=True, default='', help_text='Optimized URL slug path.', max_length=255)),
                ('schema_json_ld', models.JSONField(blank=True, default=dict, help_text='Structured JSON-LD schema markup (Article, FAQPage, WebPage, etc.).')),
                ('generated_content', models.JSONField(blank=True, default=dict, help_text='Raw structured response payload from the AI writer.')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, help_text='Model name, grounded sources, and generation parameters.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='generated', help_text='Editorial workflow status (draft, generating, generated, reviewed, approved, published, archived).', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the draft was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the draft was last updated.')),
                ('brief', models.ForeignKey(help_text='The source SEO content brief used to generate this draft.', on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='seo.seocontentbrief')),
                ('insight', models.ForeignKey(blank=True, help_text='Optional originating SEO insight.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to='seo.seoinsight')),
                ('project', models.ForeignKey(help_text='The project this content draft belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='projects.project')),
                ('recommendation', models.ForeignKey(blank=True, help_text='Optional originating SEO recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to='seo.seorecommendation')),
            ],
            options={
                'verbose_name': 'SEO content draft',
                'verbose_name_plural': 'SEO content drafts',
                'db_table': 'seo_content_drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_draft_proj_stat_idx'), models.Index(fields=['project', 'content_type'], name='seo_draft_proj_type_idx'), models.Index(fields=['brief', 'status'], name='seo_draft_brief_stat_idx'), models.Index(fields=['project', '-created_at'], name='seo_draft_proj_date_idx')],
            },
        ),
    ]
