# Generated by Django 4.2.11 on 2026-08-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0010_seocontentdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Concise title for the executable SEO task.', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of why this action is required and expected SEO impact.')),
                ('action_type', models.CharField(choices=[('update_title', 'Update Title'), ('update_meta_description', 'Update Meta Description'), ('update_slug', 'Update Slug'), ('optimize_existing_content', 'Optimize Existing Content'), ('publish_new_content', 'Publish New Content'), ('add_internal_links', 'Add Internal Links'), ('add_structured_data', 'Add Structured Data'), ('technical_seo_fix', 'Technical SEO Fix'), ('content_refresh', 'Content Refresh')], db_index=True, default='optimize_existing_content', help_text='Type of SEO task (title, meta description, publishing, structured data, etc.).', max_length=50)),
                ('target_url', models.CharField(blank=True, default='', help_text='Target URL on the project website where the action will be applied.', max_length=500)),
                ('target_keyword', models.CharField(blank=True, default='', help_text='Primary target search keyword query.', max_length=255)),
                ('current_state', models.JSONField(blank=True, default=dict, help_text='Snapshot of existing website metadata, metrics, or content before applying the action.')),
                ('proposed_change', models.JSONField(blank=True, default=dict, help_text='Structured proposal of changes to apply (e.g. new title, meta description, publishing package, schema markup).')),
                ('implementation_instructions', models.TextField(help_text='Step-by-step instructions for marketers, SEO specialists, or developers.')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='high', help_text='Execution priority level.', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('ready_to_execute', 'Ready to Execute'), ('executing', 'Executing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', help_text='Human approval workflow status (proposed, reviewed, approved, ready_to_execute, executing, completed, rejected, failed, cancelled).', max_length=30)),
                ('assigned_to', models.CharField(blank=True, default='', help_text='Person or team responsible for executing or reviewing this action.', max_length=100)),
                ('execution_metadata', models.JSONField(blank=True, default=dict, help_text='Safe execution execution logs, timestamps, target endpoints, monitoring baselines, and results.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the action was completed or executed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the action was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the action was last modified.')),
                ('brief', models.ForeignKey(blank=True, help_text='Optional originating SEO content brief.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='seo.seocontentbrief')),
                ('draft', models.ForeignKey(blank=True, help_text='Optional originating SEO content draft.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='seo.seocontentdraft')),
                ('project', models.ForeignKey(help_text='The project this SEO action belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.project')),
                ('recommendation', models.ForeignKey(blank=True, help_text='Optional originating SEO recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='seo.seorecommendation')),
            ],
            options={
                'verbose_name': 'SEO action',
                'verbose_name_plural': 'SEO actions',
                'db_table': 'seo_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_act_proj_stat_idx'), models.Index(fields=['project', 'action_type'], name='seo_act_proj_type_idx'), models.Index(fields=['project', 'priority'], name='seo_act_proj_prio_idx'), models.Index(fields=['recommendation', 'status'], name='seo_act_rec_stat_idx'), models.Index(fields=['draft', 'status'], name='seo_act_draft_stat_idx'), models.Index(fields=['project', '-created_at'], name='seo_act_proj_date_idx')],
            },
        ),
    ]
