# Generated by Django 4.2.11 on 2026-08-28 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('seo', '0011_seoaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(help_text='The high-level SEO objective or task for the agent.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_for_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current execution status of the agent run.', max_length=30)),
                ('plan', models.JSONField(blank=True, default=list, help_text='Structured list of planned sub-tasks or milestones.')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of project SEO state and baseline metrics when run started.')),
                ('max_steps', models.PositiveIntegerField(default=15, help_text='Maximum allowed reasoning/execution steps to prevent unbounded execution loops.')),
                ('total_steps', models.PositiveIntegerField(default=0, help_text='Total steps executed so far during this run.')),
                ('summary', models.TextField(blank=True, default='', help_text='Final executive summary or conclusion of the agent run.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the agent run was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the agent run was last modified.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the agent run reached a terminal state (completed, failed, cancelled).', null=True)),
                ('project', models.ForeignKey(help_text='The project this agent execution run belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='projects.project')),
                ('user', models.ForeignKey(help_text='The user who initiated this agent run.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent run',
                'verbose_name_plural': 'Agent runs',
                'db_table': 'seo_agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequential 1-indexed step number within the run.')),
                ('thought', models.TextField(blank=True, default='', help_text='Internal reasoning or thought process of the agent at this step.')),
                ('action_type', models.CharField(choices=[('plan', 'Plan'), ('tool_call', 'Tool Call'), ('observation', 'Observation'), ('decision', 'Decision'), ('final', 'Final'), ('approval', 'Approval')], db_index=True, default='plan', help_text='Type of action taken in this step (plan, tool_call, observation, decision, final, approval).', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('waiting', 'Waiting')], db_index=True, default='pending', help_text='Execution status of this step.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this step was created.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when this step completed execution.', null=True)),
                ('run', models.ForeignKey(help_text='The agent run session this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='seo.agentrun')),
            ],
            options={
                'verbose_name': 'Agent step',
                'verbose_name_plural': 'Agent steps',
                'db_table': 'seo_agent_steps',
                'ordering': ['run', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, help_text='The identifier/name of the invoked tool.', max_length=150)),
                ('tool_input', models.JSONField(blank=True, default=dict, help_text='Structured JSON arguments passed to the tool.')),
                ('tool_output', models.JSONField(blank=True, default=dict, help_text='Structured JSON output or observation returned by the tool.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message or stack summary if tool execution failed.')),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Execution latency of the tool call in milliseconds.')),
                ('is_mutating', models.BooleanField(default=False, help_text='Whether this tool invocation changes external or persistent database state.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the tool call was initiated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the tool call finished execution.', null=True)),
                ('step', models.ForeignKey(help_text='The agent step in which this tool was invoked.', on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='seo.agentstep')),
            ],
            options={
                'verbose_name': 'Agent tool call',
                'verbose_name_plural': 'Agent tool calls',
                'db_table': 'seo_agent_tool_calls',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['step', 'tool_name'], name='seo_agent_tc_step_name_idx'), models.Index(fields=['tool_name'], name='seo_agent_tc_name_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'step_number'], name='seo_agent_step_run_num_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'status'], name='seo_agent_step_run_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_number'), name='unique_agent_run_step_number'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', 'status'], name='seo_agent_run_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['user', 'status'], name='seo_agent_run_user_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', '-created_at'], name='seo_agent_run_proj_date_idx'),
        ),
    ]
