# Generated by Django 4.2.11 on 2026-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_agentrun_agentstep_agenttoolcall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconsoleconnection',
            name='encrypted_refresh_token',
            field=models.TextField(blank=True, help_text='AES-encrypted OAuth2 refresh token.', null=True),
        ),
        migrations.AddField(
            model_name='searchconsoleconnection',
            name='google_account_email',
            field=models.CharField(blank=True, help_text='Google user account email used for OAuth authorization.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchconsoleconnection',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='OAuth2 scopes granted by the user.'),
        ),
        migrations.AddField(
            model_name='searchconsoleconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp of the active access token.', null=True),
        ),
    ]
