# Generated by Django 4.2.11 on 2026-09-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0013_add_search_console_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of human approval.', null=True),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who explicitly approved this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seo_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='effort_estimate',
            field=models.CharField(default='low', help_text='Estimated effort (low, medium, high).', max_length=20),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Structured evidence snapshot (GSC metrics, audit issues, observed facts, inferences, confidence).'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when executor began applying the action.', null=True),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='failure_reason',
            field=models.TextField(blank=True, default='', help_text='Detailed error message if execution failed.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='impact_estimate',
            field=models.CharField(default='medium', help_text='Estimated impact (low, medium, high).', max_length=20),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='investigation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional originating SEO investigation reference ID.', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='opportunity_type',
            field=models.CharField(blank=True, default='', help_text='Originating SEO opportunity classification.', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Detailed causal reasoning and justification for the proposed action.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of rejection.', null=True),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who rejected this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_seo_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Mandatory explanation given by human reviewer when rejecting.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='requires_human_approval',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this action mutates state and requires explicit human sign-off.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='risk_level',
            field=models.CharField(db_index=True, default='low', help_text='Evaluated risk level (low, medium, high).', max_length=20),
        ),
        migrations.AlterField(
            model_name='seoaction',
            name='action_type',
            field=models.CharField(choices=[('update_title', 'Update Title'), ('update_meta_description', 'Update Meta Description'), ('update_slug', 'Update Slug'), ('optimize_existing_content', 'Optimize Existing Content'), ('publish_new_content', 'Publish New Content'), ('add_internal_links', 'Add Internal Links'), ('add_structured_data', 'Add Structured Data'), ('technical_seo_fix', 'Technical SEO Fix'), ('content_refresh', 'Content Refresh'), ('optimize_title', 'Optimize Title'), ('optimize_meta_description', 'Optimize Meta Description'), ('fix_missing_h1', 'Fix Missing H1'), ('fix_canonical', 'Fix Canonical'), ('fix_image_alt', 'Fix Image Alt'), ('fix_broken_link', 'Fix Broken Link'), ('improve_content', 'Improve Content'), ('investigate_performance', 'Investigate Performance'), ('monitor', 'Monitor'), ('no_action', 'No Action')], db_index=True, default='optimize_existing_content', help_text='Type of SEO task (title, meta description, publishing, structured data, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='seoaction',
            name='execution_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Safe execution logs, timestamps, target endpoints, monitoring baselines, and results.'),
        ),
        migrations.AlterField(
            model_name='seoaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending_approval', 'Pending Approval'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('ready_to_execute', 'Ready to Execute'), ('executing', 'Executing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_approval', help_text='Human approval workflow status.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='seoaction',
            index=models.Index(fields=['investigation_id'], name='seo_act_inv_id_idx'),
        ),
    ]
