# Generated by Django 4.2.11 on 2026-09-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0015_seoactionplan_seoaction_verification_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOActionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_state', models.CharField(choices=[('not_executed', 'Not Executed'), ('executed', 'Executed'), ('execution_failed', 'Execution Failed')], db_index=True, default='not_executed', help_text='Execution state of the action.', max_length=30)),
                ('verification_state', models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified'), ('verification_failed', 'Verification Failed'), ('partially_verified', 'Partially Verified')], db_index=True, default='not_verified', help_text='Empirical live verification state of the action changes.', max_length=30)),
                ('seo_outcome', models.CharField(choices=[('improved', 'Improved'), ('no_change', 'No Change'), ('declined', 'Declined'), ('unknown', 'Unknown'), ('insufficient_data', 'Insufficient Data')], db_index=True, default='unknown', help_text='Deterministic SEO performance outcome classification.', max_length=30)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Bounded confidence score (0.0 - 1.0) in the outcome determination.')),
                ('evidence_quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient')], default='insufficient', help_text='Quality and statistical strength of available observation data.', max_length=20)),
                ('measurement_window_days', models.PositiveIntegerField(default=14, help_text='Number of days evaluated before and after execution.')),
                ('measured_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the outcome was measured or last recalculated.')),
                ('before_metrics', models.JSONField(blank=True, default=dict, help_text='Baseline pre-action performance metrics (impressions, clicks, ctr, position, dates).')),
                ('after_metrics', models.JSONField(blank=True, default=dict, help_text='Post-action observation metrics (impressions, clicks, ctr, position, dates).')),
                ('metric_deltas', models.JSONField(blank=True, default=dict, help_text='Calculated deltas and percentage shifts across search metrics.')),
                ('technical_evidence', models.JSONField(blank=True, default=dict, help_text='Audit defect resolution status and crawl diagnostics evidence.')),
                ('verification_evidence', models.JSONField(blank=True, default=dict, help_text='Live HTML and metadata verification evidence.')),
                ('explanation', models.TextField(blank=True, default='', help_text='Deterministic human-readable explanation of why this outcome was assigned.')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Structured list of bullet rationale points explaining the conclusion.')),
                ('is_statistically_significant', models.BooleanField(default=False, help_text='Whether metric movement exceeds variance and sample thresholds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO action outcome',
                'verbose_name_plural': 'SEO action outcomes',
                'db_table': 'seo_action_outcomes',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='seoactionplan',
            name='outcome_measured_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when plan outcome was last measured.', null=True),
        ),
        migrations.AddField(
            model_name='seoactionplan',
            name='outcome_status',
            field=models.CharField(choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('ineffective', 'Ineffective'), ('declined', 'Declined'), ('unknown', 'Unknown'), ('insufficient_data', 'Insufficient Data')], db_index=True, default='unknown', help_text='Measured real-world SEO effectiveness outcome for this plan.', max_length=30),
        ),
        migrations.AddField(
            model_name='seoactionplan',
            name='outcome_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary breakdown of action outcomes, deltas, and effectiveness rates.'),
        ),
        migrations.AddIndex(
            model_name='seoactionplan',
            index=models.Index(fields=['outcome_status'], name='seo_plan_out_stat_idx'),
        ),
        migrations.AddField(
            model_name='seoactionoutcome',
            name='action',
            field=models.OneToOneField(help_text='The specific SEO action this outcome evaluates.', on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='seo.seoaction'),
        ),
        migrations.AddField(
            model_name='seoactionoutcome',
            name='project',
            field=models.ForeignKey(help_text='The project this outcome measurement belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='action_outcomes', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='seoactionoutcome',
            index=models.Index(fields=['project', 'seo_outcome'], name='seo_out_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='seoactionoutcome',
            index=models.Index(fields=['project', '-measured_at'], name='seo_out_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='seoactionoutcome',
            index=models.Index(fields=['execution_state', 'verification_state'], name='seo_out_exec_verif_idx'),
        ),
    ]
