# Generated by Django 4.2.11 on 2026-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0016_seoactionoutcome_seoactionplan_outcome_measured_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoactionoutcome',
            name='action',
        ),
        migrations.RemoveField(
            model_name='seoactionoutcome',
            name='project',
        ),
        migrations.RemoveIndex(
            model_name='seoactionplan',
            name='seo_plan_out_stat_idx',
        ),
        migrations.RemoveField(
            model_name='seoactionplan',
            name='outcome_status',
        ),
        migrations.AddField(
            model_name='seoaction',
            name='outcome_confidence',
            field=models.FloatField(default=0.0, help_text='Bounded confidence score (0.0 to 1.0) in the measured SEO outcome.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='outcome_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Empirical evidence, baseline vs post-execution metrics, issue resolution state, and explanation.'),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='outcome_measured_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the SEO outcome was measured.', null=True),
        ),
        migrations.AddField(
            model_name='seoaction',
            name='seo_outcome',
            field=models.CharField(choices=[('improved', 'Improved'), ('no_change', 'No Change'), ('declined', 'Declined'), ('unknown', 'Unknown'), ('insufficient_data', 'Insufficient Data')], db_index=True, default='unknown', help_text='Measured post-execution SEO outcome (improved, no_change, declined, unknown, insufficient_data).', max_length=30),
        ),
        migrations.AddField(
            model_name='seoactionplan',
            name='outcome_confidence',
            field=models.FloatField(default=0.0, help_text='Bounded confidence score (0.0 to 1.0) in the measured SEO outcome.'),
        ),
        migrations.AddField(
            model_name='seoactionplan',
            name='seo_outcome',
            field=models.CharField(choices=[('improved', 'Improved'), ('no_change', 'No Change'), ('declined', 'Declined'), ('unknown', 'Unknown'), ('insufficient_data', 'Insufficient Data')], db_index=True, default='unknown', help_text='Measured post-execution SEO outcome (improved, no_change, declined, unknown, insufficient_data).', max_length=30),
        ),
        migrations.AlterField(
            model_name='seoactionplan',
            name='outcome_measured_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the SEO outcome was measured.', null=True),
        ),
        migrations.AlterField(
            model_name='seoactionplan',
            name='outcome_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated post-execution outcome breakdown, statistical trends, and effectiveness.'),
        ),
        migrations.AddIndex(
            model_name='seoaction',
            index=models.Index(fields=['seo_outcome'], name='seo_act_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='seoactionplan',
            index=models.Index(fields=['seo_outcome'], name='seo_plan_outcome_idx'),
        ),
        migrations.DeleteModel(
            name='SEOActionOutcome',
        ),
    ]
