# Generated by Django 4.2.11 on 2026-09-15 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('seo', '0017_remove_seoactionoutcome_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(help_text='High-level operational SEO objective or ongoing monitoring goal.')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='active', help_text='Current operational state of the continuous operation.', max_length=30)),
                ('schedule_type', models.CharField(choices=[('interval_minutes', 'Every N Minutes'), ('interval_hours', 'Every N Hours'), ('daily', 'Daily')], default='interval_minutes', help_text='Recurrence schedule type: interval_minutes, interval_hours, or daily.', max_length=30)),
                ('interval_value', models.PositiveIntegerField(default=30, help_text='Frequency interval unit (e.g. 30 for 30 min, 2 for 2 hours, 1 for daily).')),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text='Structured execution parameters (workflow, target_url, target_query, max_steps, etc.).')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='Calculated timestamp when the next AgentRun should be triggered by the scheduler.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Timestamp when the most recent run was initiated.', null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed runs since last success (for circuit breaking / backoff).')),
                ('max_consecutive_failures', models.PositiveIntegerField(default=5, help_text='Maximum consecutive failures allowed before transitioning to terminal FAILED status.')),
                ('failed_run_id', models.PositiveIntegerField(blank=True, help_text='Identifier of the most recently failed AgentRun.', null=True)),
                ('failure_category', models.CharField(blank=True, default='', help_text='Categorization of recent failure (e.g. execution_failure, timeout, circuit_breaker).', max_length=50)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Sanitized summary of the failure reason from the failed run.')),
                ('total_runs', models.PositiveIntegerField(default=0, help_text='Total number of AgentRuns launched under this continuous operation.')),
                ('successful_runs', models.PositiveIntegerField(default=0, help_text='Total count of successfully completed AgentRuns.')),
                ('failed_runs', models.PositiveIntegerField(default=0, help_text='Total count of failed AgentRuns.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Persisted operational runtime statistics (duplicate_prevention_count, avg_duration, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the continuous operation was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the continuous operation was last updated.')),
                ('paused_at', models.DateTimeField(blank=True, help_text='Timestamp when the operation was paused.', null=True)),
                ('resumed_at', models.DateTimeField(blank=True, help_text='Timestamp when the operation was resumed.', null=True)),
            ],
            options={
                'verbose_name': 'Continuous operation',
                'verbose_name_plural': 'Continuous operations',
                'db_table': 'seo_continuous_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='continuousoperation',
            name='current_run',
            field=models.ForeignKey(blank=True, help_text='The currently executing AgentRun, if any (enforces at most one active run).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_continuous_operation', to='seo.agentrun'),
        ),
        migrations.AddField(
            model_name='continuousoperation',
            name='last_run',
            field=models.ForeignKey(blank=True, help_text='The most recently completed or attempted AgentRun.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_continuous_operation', to='seo.agentrun'),
        ),
        migrations.AddField(
            model_name='continuousoperation',
            name='last_successful_run',
            field=models.ForeignKey(blank=True, help_text='The most recently succeeded AgentRun.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_continuous_operations', to='seo.agentrun'),
        ),
        migrations.AddField(
            model_name='continuousoperation',
            name='project',
            field=models.ForeignKey(help_text='The project this continuous agent operation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='continuous_operations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='continuousoperation',
            name='user',
            field=models.ForeignKey(help_text='The user who created/initiated this continuous operation.', on_delete=django.db.models.deletion.CASCADE, related_name='continuous_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='continuous_operation',
            field=models.ForeignKey(blank=True, help_text='The continuous operational lifecycle session this run was scheduled under, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='seo.continuousoperation'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['continuous_operation', '-created_at'], name='seo_agent_run_cont_date_idx'),
        ),
        migrations.AddIndex(
            model_name='continuousoperation',
            index=models.Index(fields=['project', 'status'], name='seo_cont_op_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='continuousoperation',
            index=models.Index(fields=['status', 'next_run_at'], name='seo_cont_op_stat_next_idx'),
        ),
        migrations.AddIndex(
            model_name='continuousoperation',
            index=models.Index(fields=['project', '-created_at'], name='seo_cont_op_proj_date_idx'),
        ),
    ]
