# Generated by Django 4.2.11 on 2026-09-15 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0018_continuousoperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ranking_change', 'Ranking Change'), ('page_status_change', 'Page Status Change'), ('seo_audit_change', 'SEO Audit Change'), ('gsc_change', 'Google Search Console Performance Change'), ('crawl_issue', 'Crawl Issue Detected'), ('keyword_visibility_change', 'Keyword Visibility Change'), ('content_change', 'Content Change Detected')], db_index=True, help_text='Controlled classification of the SEO event.', max_length=64)),
                ('source', models.CharField(db_index=True, help_text='Originating system or component that generated this event.', max_length=128)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Severity level determining priority and trigger eligibility.', max_length=32)),
                ('status', models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('processed', 'Processed'), ('suppressed', 'Suppressed'), ('deduplicated', 'Deduplicated'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='received', help_text='Current lifecycle state of the event.', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured JSON payload containing event metrics and context.')),
                ('correlation_id', models.CharField(db_index=True, help_text='Unique identifier linking this event across workflows and runs.', max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Deterministic deduplication key to prevent duplicate runs.', max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the underlying event actually occurred.')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the event was ingested by DoxaRank.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when event trigger processing completed.', null=True)),
                ('suppression_reason', models.CharField(blank=True, default='', help_text='Explanation if event was suppressed by cooldown or storm policy.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this event record was persisted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this event record was last updated.')),
                ('agent_run', models.ForeignKey(blank=True, help_text='The AgentRun triggered by this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggering_events', to='seo.agentrun')),
                ('continuous_operation', models.ForeignKey(blank=True, help_text='Optional continuous operation session linked to this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to='seo.continuousoperation')),
                ('project', models.ForeignKey(help_text='The project this SEO event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='seo_events', to='projects.project')),
            ],
            options={
                'verbose_name': 'SEO event',
                'verbose_name_plural': 'SEO events',
                'db_table': 'seo_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'event_type', 'created_at'], name='seo_ev_proj_type_idx'), models.Index(fields=['project', 'idempotency_key'], name='seo_ev_proj_idemp_idx'), models.Index(fields=['status', 'created_at'], name='seo_ev_status_idx'), models.Index(fields=['occurred_at'], name='seo_ev_occurred_idx')],
            },
        ),
    ]
