# Generated by Django 4.2.11 on 2026-09-15 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0019_seoevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(choices=[('ranking', 'Ranking Monitor'), ('page_status', 'Page Status Monitor'), ('seo_audit', 'SEO Audit Monitor'), ('keyword_visibility', 'Keyword Visibility Monitor')], db_index=True, help_text='Monitor type that captured this snapshot.', max_length=32)),
                ('metric_key', models.CharField(db_index=True, help_text='Identifier of the entity or metric being monitored.', max_length=128)),
                ('value', models.JSONField(default=dict, help_text='Observed snapshot value payload.')),
                ('baseline_value', models.JSONField(blank=True, default=dict, help_text='Baseline reference at the time of snapshot.')),
                ('delta', models.JSONField(blank=True, default=dict, help_text='Computed difference relative to baseline.')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('anomaly', 'Anomaly Detected'), ('recovered', 'Recovered')], db_index=True, default='healthy', help_text='Health status classification at snapshot time.', max_length=32)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, help_text='Whether this snapshot exceeded threshold and represented an anomaly.')),
                ('is_recovery', models.BooleanField(default=False, help_text='Whether this snapshot marked a transition back to healthy from anomaly.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when this snapshot observation was recorded.')),
                ('project', models.ForeignKey(help_text='The project this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_snapshots', to='projects.project')),
            ],
            options={
                'verbose_name': 'monitoring snapshot',
                'verbose_name_plural': 'monitoring snapshots',
                'db_table': 'seo_monitoring_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(choices=[('ranking', 'Ranking Monitor'), ('page_status', 'Page Status Monitor'), ('seo_audit', 'SEO Audit Monitor'), ('keyword_visibility', 'Keyword Visibility Monitor')], db_index=True, help_text='Specialized monitor type responsible for this metric.', max_length=32)),
                ('metric_key', models.CharField(db_index=True, help_text='Unique identifier of the entity or metric being monitored.', max_length=128)),
                ('current_value', models.JSONField(default=dict, help_text='Latest observation payload for this metric.')),
                ('previous_value', models.JSONField(blank=True, default=dict, help_text='Observation from the preceding monitoring cycle.')),
                ('baseline_value', models.JSONField(blank=True, default=dict, help_text='Established baseline value used as reference for change detection.')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('anomaly', 'Anomaly Detected'), ('recovered', 'Recovered')], db_index=True, default='healthy', help_text='Current health classification of this monitored target.', max_length=32)),
                ('consecutive_anomalies', models.PositiveIntegerField(default=0, help_text='Number of consecutive cycles this metric remained in an anomaly state.')),
                ('snapshot_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the active snapshot observation.')),
                ('last_checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this target was last inspected by the monitoring service.')),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the observed value meaningfully changed.')),
                ('last_event_at', models.DateTimeField(blank=True, help_text='When an SEOEvent was last generated for this target.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual metadata, e.g. configured thresholds, targets, and notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this monitoring state was first established.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this monitoring state was last updated.')),
                ('last_event', models.ForeignKey(blank=True, help_text='Most recent SEOEvent triggered from this monitoring state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_states', to='seo.seoevent')),
                ('project', models.ForeignKey(help_text='The project this monitoring state belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_states', to='projects.project')),
            ],
            options={
                'verbose_name': 'monitoring state',
                'verbose_name_plural': 'monitoring states',
                'db_table': 'seo_monitoring_states',
                'ordering': ['-last_checked_at'],
                'indexes': [models.Index(fields=['project', 'monitor_type'], name='seo_mon_proj_type_idx'), models.Index(fields=['project', 'last_checked_at'], name='seo_mon_proj_checked_idx'), models.Index(fields=['status', 'last_checked_at'], name='seo_mon_status_checked_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoringstate',
            constraint=models.UniqueConstraint(fields=('project', 'monitor_type', 'metric_key'), name='seo_mon_proj_type_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='monitoringsnapshot',
            index=models.Index(fields=['project', 'monitor_type', '-created_at'], name='seo_snap_proj_type_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringsnapshot',
            index=models.Index(fields=['project', '-created_at'], name='seo_snap_proj_created_idx'),
        ),
    ]
