# Generated by Django 4.2.11 on 2026-09-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0020_monitoringsnapshot_monitoringstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending_approval', 'Pending Approval'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('ready_to_execute', 'Ready to Execute'), ('authorized', 'Authorized'), ('executing', 'Executing'), ('completed', 'Completed'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], db_index=True, default='pending_approval', help_text='Human approval workflow status.', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectRemediationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_autonomous_enabled', models.BooleanField(default=True, help_text='Whether autonomous remediation for authorized low-risk actions is permitted.')),
                ('max_daily_autonomous_actions', models.PositiveIntegerField(default=10, help_text='Maximum number of autonomous remediations allowed per calendar day.')),
                ('min_confidence_threshold', models.FloatField(default=0.85, help_text='Minimum confidence score required for an action to execute autonomously.')),
                ('allowed_autonomous_types', models.JSONField(blank=True, default=list, help_text='List of ActionType string values explicitly permitted for autonomous execution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this remediation policy applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='remediation_policy', to='projects.project')),
            ],
            options={
                'verbose_name': 'project remediation policy',
                'verbose_name_plural': 'project remediation policies',
                'db_table': 'seo_project_remediation_policies',
            },
        ),
        migrations.CreateModel(
            name='RemediationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA-256 fingerprint guaranteeing idempotency across workers and retries.', max_length=64)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', help_text='Assessed risk classification for this remediation.', max_length=20)),
                ('policy_decision', models.CharField(choices=[('autonomous_allowed', 'Autonomous Allowed'), ('human_approval_required', 'Human Approval Required'), ('blocked', 'Blocked')], db_index=True, default='human_approval_required', help_text='Centralized policy determination.', max_length=30)),
                ('policy_explanation', models.TextField(blank=True, default='', help_text='Detailed justification of the policy decision.')),
                ('is_autonomous', models.BooleanField(db_index=True, default=False, help_text='Whether this remediation was executed autonomously without human intervention.')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending_approval', 'Pending Approval'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('ready_to_execute', 'Ready to Execute'), ('authorized', 'Authorized'), ('executing', 'Executing'), ('completed', 'Completed'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', help_text='Remediation execution & verification lifecycle status.', max_length=30)),
                ('rollback_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of pre-remediation state to enable deterministic rollback.')),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Empirical verification evidence collected post-execution.')),
                ('error_category', models.CharField(blank=True, choices=[('tool_failure', 'Tool Failure'), ('authorization_failure', 'Authorization Failure'), ('human_rejection', 'Human Rejection'), ('execution_timeout', 'Execution Timeout'), ('verification_failure', 'Verification Failure'), ('tenant_isolation_failure', 'Tenant Isolation Failure'), ('policy_block', 'Policy Block'), ('idempotency_conflict', 'Idempotency Conflict')], db_index=True, default='', help_text='Deterministic failure category if execution or verification fails.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='The underlying SEO action being remediated.', on_delete=django.db.models.deletion.CASCADE, related_name='remediation_records', to='seo.seoaction')),
                ('agent_run', models.ForeignKey(blank=True, help_text='The multi-agent run orchestrating this remediation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_records', to='seo.agentrun')),
                ('event', models.ForeignKey(blank=True, help_text='The originating SEO event triggering this remediation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_records', to='seo.seoevent')),
                ('project', models.ForeignKey(help_text='The project this remediation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='remediation_records', to='projects.project')),
            ],
            options={
                'verbose_name': 'remediation record',
                'verbose_name_plural': 'remediation records',
                'db_table': 'seo_remediation_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_rem_proj_stat_idx'), models.Index(fields=['action', 'status'], name='seo_rem_act_stat_idx'), models.Index(fields=['project', '-created_at'], name='seo_rem_proj_created_idx'), models.Index(fields=['policy_decision'], name='seo_rem_decision_idx')],
                'unique_together': {('project', 'idempotency_key')},
            },
        ),
    ]
