# Generated by Django 4.2.11 on 2026-09-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0021_alter_seoaction_status_projectremediationpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('cms', 'CMS'), ('git', 'Git'), ('webhook', 'Webhook/API')], db_index=True, help_text='External system category: cms, git, or webhook.', max_length=30)),
                ('provider', models.CharField(help_text='Provider identifier (e.g. wordpress, shopify, github, gitlab, generic_webhook).', max_length=60)),
                ('name', models.CharField(help_text='Human-readable name for this external connection.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('test_staging', 'Test/Staging')], db_index=True, default='test_staging', help_text='Connection operational status.', max_length=30)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Non-secret configuration: baseUrl, allowlisted_domains, branch_prefix, repo name, etc.')),
                ('encrypted_credentials', models.TextField(blank=True, default='', help_text='AES-Fernet encrypted JSON string storing tokens/credentials.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The project this external connection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='external_connections', to='projects.project')),
            ],
            options={
                'verbose_name': 'external connection',
                'verbose_name_plural': 'external connections',
                'db_table': 'seo_external_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', help_text='Correlation ID with AgentTask in DynamicTaskPlanner DAG.', max_length=64)),
                ('correlation_id', models.CharField(db_index=True, help_text='Unique request/trace correlation ID across agents and adapters.', max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA-256 fingerprint guaranteeing idempotency across workers and retries.', max_length=64)),
                ('system_type', models.CharField(db_index=True, help_text='External system type (cms, git, webhook).', max_length=30)),
                ('provider', models.CharField(help_text='Provider identifier (wordpress, shopify, github, generic_webhook, etc.).', max_length=60)),
                ('operation', models.CharField(db_index=True, help_text='Specific operation (e.g. read_metadata, update_metadata, create_branch, write_file, send_webhook).', max_length=100)),
                ('required_capability', models.CharField(help_text='Explicit capability required (e.g. CMS.UPDATE_METADATA, GIT.WRITE_FILE).', max_length=100)),
                ('target', models.CharField(help_text='Target URL, repo/branch, or endpoint.', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('executing', 'Executing'), ('completed', 'Completed'), ('verified', 'Verified'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Lifecycle status of the external operation.', max_length=40)),
                ('risk_level', models.CharField(db_index=True, default='low', help_text='Assessed risk level (low, medium, high, critical).', max_length=20)),
                ('is_autonomous', models.BooleanField(db_index=True, default=False, help_text='Whether operation was executed autonomously under policy.')),
                ('request_summary', models.JSONField(blank=True, default=dict, help_text='Sanitized summary of request parameters (secrets stripped).')),
                ('before_state', models.JSONField(blank=True, default=dict, help_text='Captured pre-operation state for verification and rollback.')),
                ('after_state', models.JSONField(blank=True, default=dict, help_text='Resulting state captured post-operation.')),
                ('response_summary', models.JSONField(blank=True, default=dict, help_text='Sanitized response metadata, status code, and duration.')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP or adapter execution status code.', null=True)),
                ('changed', models.BooleanField(default=False, help_text='Whether external system state was actually modified.')),
                ('error_category', models.CharField(blank=True, db_index=True, default='', help_text='Categorized error code on failure.', max_length=60)),
                ('error_message', models.TextField(blank=True, default='', help_text='Sanitized error description.')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of bounded retries attempted.')),
                ('duration_ms', models.IntegerField(default=0, help_text='Operation duration in milliseconds.')),
                ('verification_status', models.CharField(db_index=True, default='pending', help_text='Post-operation empirical verification status: pending, verified, failed.', max_length=30)),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Empirical verification evidence collected post-execution.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, help_text='Optional SEOAction associated with this external operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_operations', to='seo.seoaction')),
                ('agent_run', models.ForeignKey(blank=True, help_text='The agent run executing or orchestrating this external operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_operations', to='seo.agentrun')),
                ('connection', models.ForeignKey(blank=True, help_text='The external connection used for this operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='seo.externalconnection')),
                ('project', models.ForeignKey(help_text='The project this external operation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='external_operations', to='projects.project')),
                ('remediation_record', models.ForeignKey(blank=True, help_text='Optional RemediationRecord associated with this external operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_operations', to='seo.remediationrecord')),
            ],
            options={
                'verbose_name': 'external operation',
                'verbose_name_plural': 'external operations',
                'db_table': 'seo_external_operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'system_type'], name='seo_extop_proj_sys_idx'), models.Index(fields=['project', 'status'], name='seo_extop_proj_stat_idx'), models.Index(fields=['correlation_id'], name='seo_extop_corr_idx'), models.Index(fields=['project', '-created_at'], name='seo_extop_proj_created_idx')],
                'unique_together': {('project', 'idempotency_key')},
            },
        ),
        migrations.AddIndex(
            model_name='externalconnection',
            index=models.Index(fields=['project', 'system_type'], name='seo_extconn_proj_sys_idx'),
        ),
        migrations.AddIndex(
            model_name='externalconnection',
            index=models.Index(fields=['project', 'status'], name='seo_extconn_proj_stat_idx'),
        ),
    ]
