# Generated by Django 4.2.11 on 2026-09-18 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0022_externalconnection_externaloperationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermSEOStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the long-term SEO strategy.', max_length=255)),
                ('version', models.PositiveIntegerField(db_index=True, default=1, help_text='Strategy version number (1, 2, 3...).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed (Awaiting HITL Approval)'), ('active', 'Active'), ('superseded', 'Superseded by Newer Version'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Status of this strategy version.', max_length=20)),
                ('health', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track'), ('no_data', 'No Data')], db_index=True, default='on_track', help_text='Derived strategic health: on_track, at_risk, off_track, no_data.', max_length=20)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Start of the effective strategic period.')),
                ('effective_until', models.DateTimeField(blank=True, help_text='End of the effective strategic period.', null=True)),
                ('rationale', models.TextField(blank=True, default='', help_text='Structured strategic rationale explaining priorities and approach.')),
                ('assumptions', models.JSONField(blank=True, default=list, help_text='Explicit operating baseline assumptions.')),
                ('risks', models.JSONField(blank=True, default=list, help_text='Identified strategic risks and mitigation paths.')),
                ('expected_outcomes', models.JSONField(blank=True, default=list, help_text='Measurable expected outcomes over the planning horizon.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting historical GSC, ranking, audit, and monitoring evidence.')),
                ('adjustment_reason', models.TextField(blank=True, default='', help_text='Explanation of why this strategy version was created or adjusted.')),
                ('created_by_agent', models.CharField(default='seo_strategist', help_text='Agent or system component that generated this strategy.', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of human authorization.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who authorized this strategy version under HITL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous strategy version this version adjusted or superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='seo.longtermseostrategy')),
                ('project', models.ForeignKey(help_text='Associated project for this strategy.', on_delete=django.db.models.deletion.CASCADE, related_name='long_term_strategies', to='projects.project')),
            ],
            options={
                'verbose_name': 'long-term SEO strategy',
                'verbose_name_plural': 'long-term SEO strategies',
                'db_table': 'seo_long_term_strategies',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the strategic objective.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed context, rationale, and strategic intent.')),
                ('metric', models.CharField(db_index=True, help_text='Target metric (e.g. organic_traffic, average_position, indexed_pages, technical_health_score, amharic_keyword_growth).', max_length=100)),
                ('baseline', models.FloatField(default=0.0, help_text='Initial baseline metric value at start of objective.')),
                ('target', models.FloatField(default=0.0, help_text='Target metric value to achieve.')),
                ('target_direction', models.CharField(choices=[('increasing', 'Increasing (Higher is Better)'), ('decreasing', 'Decreasing (Lower is Better, e.g. Rank)')], default='increasing', help_text='Direction: increasing (higher is better) or decreasing (lower is better, e.g. rank).', max_length=20)),
                ('current_value', models.FloatField(default=0.0, help_text='Latest observed or computed metric value.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Objective inception date.')),
                ('target_date', models.DateTimeField(help_text='Target deadline for objective completion.')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Strategic priority rank.', max_length=20)),
                ('horizon', models.CharField(choices=[('short_term', 'Short-Term (Days to Weeks)'), ('medium_term', 'Medium-Term (Weeks to Months)'), ('long_term', 'Long-Term (Months to Year)')], db_index=True, default='medium_term', help_text='Strategic horizon (short_term, medium_term, long_term).', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('at_risk', 'At Risk'), ('achieved', 'Achieved'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', help_text='Lifecycle status of the objective.', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Derived progress score normalized between 0.0 and 1.0 (or >1.0 if exceeded).')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting empirical evidence, baseline observations, and provenance references.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Associated project for this strategic objective.', on_delete=django.db.models.deletion.CASCADE, related_name='strategic_objectives', to='projects.project')),
            ],
            options={
                'verbose_name': 'strategic objective',
                'verbose_name_plural': 'strategic objectives',
                'db_table': 'seo_strategic_objectives',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the strategic initiative.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Scope and methodology for this body of work.')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Execution priority.', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='planned', help_text='Lifecycle status of the initiative.', max_length=20)),
                ('horizon', models.CharField(choices=[('short_term', 'Short-Term (Days to Weeks)'), ('medium_term', 'Medium-Term (Weeks to Months)'), ('long_term', 'Long-Term (Months to Year)')], db_index=True, default='medium_term', help_text='Strategic planning horizon.', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Target initiative start date.')),
                ('target_date', models.DateTimeField(blank=True, help_text='Target completion date.', null=True)),
                ('progress', models.FloatField(default=0.0, help_text='Completion progress normalized between 0.0 and 1.0.')),
                ('risk_level', models.CharField(default='low', help_text='Assessed risk level: low, medium, high, critical.', max_length=20)),
                ('owner', models.CharField(default='seo_action_planner', help_text='Agent role or user responsible for executing this initiative.', max_length=100)),
                ('target_action_types', models.JSONField(blank=True, default=list, help_text='List of ActionType names targeted by this initiative (e.g. meta_tags, content, technical).')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting evidence and progress audit trails.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan', models.ForeignKey(blank=True, help_text='Concrete execution action plan linked to this initiative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_initiatives', to='seo.seoactionplan')),
                ('objective', models.ForeignKey(blank=True, help_text='Optional primary objective this initiative advances.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='seo.strategicobjective')),
                ('strategy', models.ForeignKey(help_text='Associated long-term strategy.', on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='seo.longtermseostrategy')),
            ],
            options={
                'verbose_name': 'strategic initiative',
                'verbose_name_plural': 'strategic initiatives',
                'db_table': 'seo_strategic_initiatives',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_cycle', models.PositiveIntegerField(default=1, help_text='Sequential review cycle number.')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', help_text='Status of the review evaluation execution.', max_length=20)),
                ('evaluation_summary', models.JSONField(default=dict, help_text='Calculated objectives progress, initiative status, detected risks, and trends.')),
                ('decision', models.CharField(choices=[('keep', 'Keep Current Strategy'), ('adjust', 'Adjust Initiatives / Objectives'), ('pause', 'Pause Strategy Execution'), ('complete', 'Complete Strategy (All Goals Achieved)'), ('replace', 'Replace with New Strategic Direction')], db_index=True, default='keep', help_text='Strategic decision reached (keep, adjust, pause, complete, replace).', max_length=20)),
                ('proposed_changes', models.JSONField(blank=True, default=dict, help_text='Proposed adjustments to strategy, objectives, or initiatives.')),
                ('approval_status', models.CharField(choices=[('not_required', 'Not Required (Low Impact / Keep)'), ('pending_approval', 'Pending Human Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_required', help_text='HITL governance status: not_required, pending_approval, approved, rejected.', max_length=30)),
                ('fingerprint', models.CharField(db_index=True, help_text='Deterministic SHA-256 fingerprint of review parameters preventing duplicate execution.', max_length=64)),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when review was performed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_reviews', to='projects.project')),
                ('strategy', models.ForeignKey(help_text='Strategy being evaluated in this review cycle.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='seo.longtermseostrategy')),
            ],
            options={
                'verbose_name': 'strategy review record',
                'verbose_name_plural': 'strategy review records',
                'db_table': 'seo_strategy_reviews',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['project', 'fingerprint'], name='seo_rev_proj_fp_idx'), models.Index(fields=['strategy', 'review_cycle'], name='seo_rev_strat_cyc_idx'), models.Index(fields=['project', '-reviewed_at'], name='seo_rev_proj_rev_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='strategicobjective',
            index=models.Index(fields=['project', 'status'], name='seo_obj_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicobjective',
            index=models.Index(fields=['project', 'metric'], name='seo_obj_proj_met_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicobjective',
            index=models.Index(fields=['project', '-created_at'], name='seo_obj_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicinitiative',
            index=models.Index(fields=['strategy', 'status'], name='seo_init_strat_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicinitiative',
            index=models.Index(fields=['objective', 'status'], name='seo_init_obj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='longtermseostrategy',
            index=models.Index(fields=['project', 'status'], name='seo_strat_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='longtermseostrategy',
            index=models.Index(fields=['project', 'version'], name='seo_strat_proj_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='longtermseostrategy',
            index=models.Index(fields=['project', '-created_at'], name='seo_strat_proj_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='longtermseostrategy',
            unique_together={('project', 'version')},
        ),
    ]
