# Generated by Django 4.2.11 on 2026-09-18 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0023_longtermseostrategy_strategicobjective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Audited action identifier (e.g. run.retried, continuous_ops.paused, circuit_breaker.reset).', max_length=128)),
                ('target_type', models.CharField(db_index=True, help_text='Entity type affected by operator action (e.g. agent_run, circuit_breaker, continuous_operation).', max_length=64)),
                ('target_id', models.CharField(db_index=True, help_text='Identifier of the entity affected.', max_length=128)),
                ('rationale', models.TextField(blank=True, default='', help_text='Operator-provided justification for manual intervention.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured metadata describing state changes before and after operator action.')),
                ('ip_address', models.CharField(blank=True, default='', help_text='Client IP address from which operator request originated.', max_length=45)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when administrative action was committed.')),
            ],
            options={
                'verbose_name': 'Operator audit log',
                'verbose_name_plural': 'Operator audit logs',
                'db_table': 'seo_operator_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, help_text='Classification of alert (e.g. high_failure_rate, circuit_breaker_opened, stale_run_detected).', max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Alert priority level.', max_length=32)),
                ('message', models.TextField(help_text='Human-readable description of alert condition.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Diagnostic runtime evidence and metrics at time of alert generation.')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Whether alert condition has been cleared or acknowledged.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when alert was resolved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Platform alert record',
                'verbose_name_plural': 'Platform alert records',
                'db_table': 'seo_platform_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformCircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, help_text='Unique identifier of the external dependency or provider (e.g. cms, git, webhook, serp, gsc, llm).', max_length=64, unique=True)),
                ('state', models.CharField(choices=[('closed', 'Closed (Healthy)'), ('open', 'Open (Tripped)'), ('half_open', 'Half-Open (Testing Recovery)')], db_index=True, default='closed', help_text='Current circuit state (closed=normal, open=fast-fail, half_open=probing).', max_length=32)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Consecutive failure count within current window.')),
                ('failure_threshold', models.PositiveIntegerField(default=5, help_text='Number of consecutive failures before tripping to OPEN.')),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, help_text='Seconds to wait in OPEN state before transitioning to HALF_OPEN probe.')),
                ('last_failure_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent registered failure.', null=True)),
                ('last_state_change_at', models.DateTimeField(auto_now=True, help_text='Timestamp when circuit state last transitioned.')),
                ('opened_reason', models.TextField(blank=True, default='', help_text='Diagnostic summary of why the circuit breaker opened.')),
                ('trip_count', models.PositiveIntegerField(default=0, help_text='Lifetime count of times this circuit breaker has tripped to OPEN.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific diagnostic state, error samples, or operator notes.')),
            ],
            options={
                'verbose_name': 'Platform circuit breaker',
                'verbose_name_plural': 'Platform circuit breakers',
                'db_table': 'seo_platform_circuit_breakers',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique idempotency key identifying the logical operation.', max_length=255, unique=True)),
                ('scope', models.CharField(db_index=True, help_text='Classification scope (e.g. run_creation, task_execution, remediation, external_op).', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Execution state of the idempotent operation.', max_length=32)),
                ('request_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of payload/arguments to verify payload consistency on duplicate calls.', max_length=64)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Cached structured response payload returned on subsequent duplicate requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when idempotency record expires and can be compacted.', null=True)),
            ],
            options={
                'verbose_name': 'Platform idempotency record',
                'verbose_name_plural': 'Platform idempotency records',
                'db_table': 'seo_platform_idempotency_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Distributed tracing correlation ID linking requests, runs, tasks, and tools.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='execution_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Resource consumption telemetry: llm_calls, tool_calls, duration_ms, external_ops.'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent worker heartbeat.', null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when worker execution lease expires.', null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed retry attempts before marking run as permanently failed.'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='recovery_status',
            field=models.CharField(db_index=True, default='none', help_text='Current recovery state: none, recovered, reconciling, failed, blocked.', max_length=32),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retries attempted for this agent run session.'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier of the Celery worker currently executing this run.', max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='seo_agent_run_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['correlation_id'], name='seo_agent_run_correl_idx'),
        ),
        migrations.AddField(
            model_name='platformidempotencyrecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project context for this idempotent operation, if scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='projects.project'),
        ),
        migrations.AddField(
            model_name='platformalertrecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project context if alert is tenant-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_alerts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='operatorauditlog',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project context if the operator action was project-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_audit_logs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='operatorauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The authenticated operator or user who performed the administrative action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformidempotencyrecord',
            index=models.Index(fields=['scope', 'status'], name='seo_idemp_scope_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='platformidempotencyrecord',
            index=models.Index(fields=['project', 'scope'], name='seo_idemp_proj_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='platformalertrecord',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='seo_alert_type_res_idx'),
        ),
        migrations.AddIndex(
            model_name='platformalertrecord',
            index=models.Index(fields=['severity', 'is_resolved'], name='seo_alert_sev_res_idx'),
        ),
        migrations.AddIndex(
            model_name='platformalertrecord',
            index=models.Index(fields=['project', '-created_at'], name='seo_alert_proj_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='seo_op_audit_act_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='seo_op_audit_tgt_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorauditlog',
            index=models.Index(fields=['project', '-timestamp'], name='seo_op_audit_proj_ts_idx'),
        ),
    ]
