# Generated by Django 4.2.11 on 2026-09-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0024_production_agent_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current execution status of the crawl job.', max_length=20)),
                ('max_pages', models.PositiveIntegerField(default=100, help_text='Maximum number of pages to crawl (capped at 500 per job).')),
                ('max_depth', models.PositiveIntegerField(default=3, help_text='Maximum BFS depth to traverse (capped at 10).')),
                ('respect_robots_txt', models.BooleanField(default=True, help_text='Whether to respect robots.txt directives during the crawl.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the crawl execution began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the crawl execution concluded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the crawl job was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the crawl job was last updated.')),
                ('pages_crawled', models.PositiveIntegerField(default=0, help_text='Number of pages successfully crawled.')),
                ('pages_discovered', models.PositiveIntegerField(default=0, help_text='Total number of unique URLs discovered during crawl.')),
                ('broken_links_count', models.PositiveIntegerField(default=0, help_text='Number of 4xx/5xx URLs found across all crawled pages.')),
                ('missing_titles_count', models.PositiveIntegerField(default=0, help_text='Number of pages with missing or empty <title> tags.')),
                ('missing_descriptions_count', models.PositiveIntegerField(default=0, help_text='Number of pages with missing meta descriptions.')),
                ('duplicate_titles_count', models.PositiveIntegerField(default=0, help_text='Number of duplicate page titles detected across crawled pages.')),
                ('missing_h1_count', models.PositiveIntegerField(default=0, help_text='Number of pages with zero H1 headings.')),
                ('redirect_chains_count', models.PositiveIntegerField(default=0, help_text='Number of URLs that include redirect chains.')),
                ('slow_pages_count', models.PositiveIntegerField(default=0, help_text='Number of pages with response times exceeding 3 seconds.')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking the background crawl worker.', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the crawl job failed.', null=True)),
                ('crawl_metadata', models.JSONField(blank=True, default=dict, help_text='Structured crawl metadata (robots.txt status, config, timings).')),
                ('project', models.ForeignKey(help_text='The project/website this crawl job belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='projects.project')),
            ],
            options={
                'verbose_name': 'crawl job',
                'verbose_name_plural': 'crawl jobs',
                'db_table': 'seo_crawl_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The canonical URL of this crawled page.', max_length=2048)),
                ('final_url', models.URLField(blank=True, help_text='Final URL after following redirects.', max_length=2048, null=True)),
                ('status_code', models.PositiveIntegerField(help_text='HTTP response status code returned for this URL.')),
                ('response_time_ms', models.FloatField(default=0.0, help_text='HTTP response time in milliseconds.')),
                ('depth', models.PositiveIntegerField(default=0, help_text='BFS depth at which this page was discovered.')),
                ('title', models.CharField(blank=True, help_text='Page <title> tag content.', max_length=512, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Page meta description content.', null=True)),
                ('h1_count', models.PositiveIntegerField(default=0, help_text='Number of H1 heading tags on this page.')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Approximate visible text word count.')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL declared on the page via <link rel="canonical">.', max_length=2048, null=True)),
                ('has_redirect', models.BooleanField(default=False, help_text='Whether this URL underwent one or more HTTP redirects.')),
                ('redirect_chain', models.JSONField(blank=True, default=list, help_text='Ordered list of intermediate redirect URLs.')),
                ('internal_links_count', models.PositiveIntegerField(default=0, help_text='Number of unique internal links found on this page.')),
                ('external_links_count', models.PositiveIntegerField(default=0, help_text='Number of unique external links found on this page.')),
                ('images_count', models.PositiveIntegerField(default=0, help_text='Total number of <img> elements found on this page.')),
                ('images_missing_alt_count', models.PositiveIntegerField(default=0, help_text='Number of images with missing or empty alt attributes.')),
                ('is_broken', models.BooleanField(db_index=True, default=False, help_text='True if this page returned a 4xx or 5xx HTTP status code.')),
                ('is_slow', models.BooleanField(db_index=True, default=False, help_text='True if response time exceeded 3000ms.')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of detected SEO issue objects for this page, e.g. [{type, severity, message}].')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this page result was recorded.')),
                ('crawl_job', models.ForeignKey(help_text='The parent crawl job this page result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='seo.crawljob')),
            ],
            options={
                'verbose_name': 'crawl page',
                'verbose_name_plural': 'crawl pages',
                'db_table': 'seo_crawl_pages',
                'ordering': ['depth', 'url'],
                'indexes': [models.Index(fields=['crawl_job', 'is_broken'], name='seo_crawl_pg_job_broken_idx'), models.Index(fields=['crawl_job', 'is_slow'], name='seo_crawl_pg_job_slow_idx'), models.Index(fields=['crawl_job', 'status_code'], name='seo_crawl_pg_job_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['project', '-created_at'], name='seo_crawl_job_project_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status'], name='seo_crawl_job_status_idx'),
        ),
    ]
