# Generated by Django 4.2.11 on 2026-09-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0025_crawljob_and_crawlpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankCheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial_failure', 'Partial Failure')], db_index=True, default='pending', help_text='Current execution status of the rank check job.', max_length=30)),
                ('total_keywords', models.PositiveIntegerField(default=0, help_text='Total number of keywords to check in this job.')),
                ('completed_keywords', models.PositiveIntegerField(default=0, help_text='Number of keywords successfully checked.')),
                ('failed_keywords', models.PositiveIntegerField(default=0, help_text='Number of keyword checks that failed.')),
                ('trigger', models.CharField(default='manual', help_text='Origin trigger: "manual", "single_keyword", "scheduled_daily".', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the ranking check began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the ranking check completed.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the job failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rank check job',
                'verbose_name_plural': 'rank check jobs',
                'db_table': 'seo_rank_check_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_domain',
            field=models.CharField(default='google.com.et', help_text='Target search engine domain (e.g. "google.com.et").', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordranking',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Diagnostic error message if ranking check failed.'),
        ),
        migrations.AddField(
            model_name='keywordranking',
            name='result_status',
            field=models.CharField(choices=[('found', 'Found in Top 100'), ('not_found', 'Not in Top 100'), ('error', 'Error / Blocked')], db_index=True, default='found', help_text='Status of the ranking observation (found, not_found, error).', max_length=30),
        ),
        migrations.AddField(
            model_name='keywordranking',
            name='search_domain',
            field=models.CharField(default='google.com.et', help_text='Target search domain (e.g. "google.com.et").', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordranking',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Page title found in SERP snippet.', max_length=500),
        ),
        migrations.AlterField(
            model_name='keywordranking',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Observed ranking position in search results (e.g. 1 for rank #1), or null if not found in top 100.', null=True),
        ),
        migrations.AddIndex(
            model_name='keywordranking',
            index=models.Index(fields=['keyword', '-recorded_at'], name='seo_kw_rk_kw_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordranking',
            index=models.Index(fields=['result_status', '-recorded_at'], name='seo_kw_rk_stat_rec_idx'),
        ),
        migrations.AddField(
            model_name='rankcheckjob',
            name='project',
            field=models.ForeignKey(help_text='The project website this ranking check job belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rank_check_jobs', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='rankcheckjob',
            index=models.Index(fields=['project', '-created_at'], name='seo_rk_job_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='rankcheckjob',
            index=models.Index(fields=['status'], name='seo_rk_job_stat_idx'),
        ),
    ]
