# Generated by Django 4.2.11 on 2026-09-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0026_rankcheckjob_keyword_search_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive label/brand name for the competitor (e.g. "Addis Insight").', max_length=200)),
                ('domain', models.CharField(db_index=True, help_text='Normalized canonical domain name (e.g. "addisinsight.net").', max_length=255)),
                ('website_url', models.URLField(blank=True, default='', help_text='Optional full website URL for the competitor.', max_length=2048)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this competitor is currently active for weekly snapshots.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The project website this competitor is monitored against.', on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='projects.project')),
            ],
            options={
                'verbose_name': 'competitor',
                'verbose_name_plural': 'competitors',
                'db_table': 'seo_competitors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorSnapshotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial_failure', 'Partial Failure')], db_index=True, default='pending', help_text='Execution status of the competitor snapshot job.', max_length=30)),
                ('total_keywords', models.PositiveIntegerField(default=0, help_text='Total number of keywords evaluated during this snapshot job.')),
                ('completed_keywords', models.PositiveIntegerField(default=0, help_text='Number of keywords successfully queried and processed.')),
                ('failed_keywords', models.PositiveIntegerField(default=0, help_text='Number of keywords whose SERP query failed.')),
                ('trigger', models.CharField(default='manual', help_text='Origin trigger: "manual" or "scheduled_weekly".', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the snapshot job execution began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the snapshot job execution concluded.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the snapshot job experienced a failure.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The project website for which competitor snapshots were run.', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_snapshot_jobs', to='projects.project')),
            ],
            options={
                'verbose_name': 'competitor snapshot job',
                'verbose_name_plural': 'competitor snapshot jobs',
                'db_table': 'seo_competitor_snapshot_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, help_text='Organic ranking position (1-100) on google.com.et, or null if NOT FOUND.', null=True)),
                ('ranking_url', models.URLField(blank=True, default='', help_text='The exact landing page URL of the competitor found in SERP.', max_length=2048)),
                ('title', models.CharField(blank=True, default='', help_text='The SERP snippet title found for the competitor.', max_length=512)),
                ('result_status', models.CharField(choices=[('found', 'Found in Top 100'), ('not_found', 'Not in Top 100'), ('error', 'Error / Blocked')], db_index=True, default='not_found', help_text='Result status: "found" (1-100), "not_found" (>100), or "error".', max_length=20)),
                ('search_engine', models.CharField(default='google', help_text='Target search engine (default: google).', max_length=50)),
                ('search_domain', models.CharField(default='google.com.et', help_text='Target Google domain (default: google.com.et for Google Ethiopia).', max_length=100)),
                ('country', models.CharField(default='ET', help_text='Target country code (default: ET).', max_length=10)),
                ('language', models.CharField(default='en', help_text='Target query language ("en" or "am").', max_length=10)),
                ('device', models.CharField(default='desktop', help_text='Target device category ("desktop" or "mobile").', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the check encountered an issue.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the snapshot was recorded.')),
                ('competitor', models.ForeignKey(help_text='The competitor domain observed in this snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='seo.competitor')),
                ('keyword', models.ForeignKey(help_text='The tracked search query/keyword.', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_snapshots', to='seo.keyword')),
                ('project', models.ForeignKey(help_text='The project tracking this competitor.', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_snapshots', to='projects.project')),
                ('snapshot_job', models.ForeignKey(blank=True, help_text='The snapshot batch job that produced this observation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='seo.competitorsnapshotjob')),
            ],
            options={
                'verbose_name': 'competitor snapshot',
                'verbose_name_plural': 'competitor snapshots',
                'db_table': 'seo_competitor_snapshots',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competitorsnapshotjob',
            index=models.Index(fields=['project', '-created_at'], name='seo_comp_job_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshotjob',
            index=models.Index(fields=['status'], name='seo_comp_job_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['competitor', '-recorded_at'], name='seo_comp_snap_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['project', '-recorded_at'], name='seo_comp_snap_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['keyword', '-recorded_at'], name='seo_comp_snap_kw_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['competitor', 'keyword', '-recorded_at'], name='seo_comp_snap_ck_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['result_status', '-recorded_at'], name='seo_comp_snap_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['project', 'is_active'], name='seo_comp_proj_active_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['domain'], name='seo_comp_domain_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('project', 'domain'), name='unique_project_competitor_domain'),
        ),
    ]
