# Generated by Django 4.2.11 on 2026-09-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('seo', '0027_competitor_competitorsnapshotjob_competitorsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitorsnapshot',
            options={'ordering': ['-recorded_at', '-id'], 'verbose_name': 'competitor snapshot', 'verbose_name_plural': 'competitor snapshots'},
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('crawler', 'Technical Crawler'), ('rank_tracker', 'Rank Tracker'), ('competitor_snapshot', 'Competitor SERP Snapshots'), ('seo_tool', 'SEO Tool'), ('system', 'System')], db_index=True, default='system', help_text='Originating system (crawler, rank_tracker, competitor_snapshot, etc).', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', help_text='Optional reference to originating entity (e.g. crawl_page_id, keyword_id).', max_length=100)),
                ('category', models.CharField(choices=[('technical_seo', 'Technical SEO'), ('on_page_seo', 'On-Page SEO'), ('performance', 'Performance'), ('indexing', 'Indexing & Crawlability'), ('rankings', 'Rankings & Visibility'), ('content', 'Content'), ('competitors', 'Competitor Intelligence')], db_index=True, default='technical_seo', help_text='Categorization of the SEO recommendation.', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='medium', help_text='Severity level: critical, high, medium, low, info.', max_length=20)),
                ('title', models.CharField(help_text='Concise, user-facing recommendation headline.', max_length=255)),
                ('description', models.TextField(help_text='Detailed breakdown: Problem detected and Why it matters.')),
                ('recommended_action', models.TextField(help_text='Concrete actionable guidance explaining what the user can do.')),
                ('affected_url', models.CharField(blank=True, default='', help_text='Specific page URL affected by this recommendation, if applicable.', max_length=1000)),
                ('affected_keyword', models.CharField(blank=True, default='', help_text='Specific tracked keyword affected by this recommendation, if applicable.', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', help_text='Lifecycle status: open, acknowledged, resolved, dismissed.', max_length=30)),
                ('priority', models.PositiveIntegerField(db_index=True, default=50, help_text='Deterministic priority score (1-100) based on severity, impact, and frequency.')),
                ('fingerprint', models.CharField(db_index=True, help_text='Deterministic deduplication key: rule_code:resource_identifier.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured contextual data and diagnostic metrics.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the recommendation was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the recommendation was last modified.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the recommendation was resolved or dismissed.', null=True)),
                ('project', models.ForeignKey(help_text='The project website this recommendation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to='projects.project')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
                'db_table': 'seo_project_recommendations',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='seo_prec_proj_stat_idx'), models.Index(fields=['project', 'severity'], name='seo_prec_proj_sev_idx'), models.Index(fields=['project', 'category'], name='seo_prec_proj_cat_idx'), models.Index(fields=['project', 'source_type'], name='seo_prec_proj_src_idx'), models.Index(fields=['project', '-priority'], name='seo_prec_proj_prio_idx'), models.Index(fields=['project', 'fingerprint'], name='seo_prec_proj_fp_idx'), models.Index(fields=['project', '-created_at'], name='seo_prec_proj_date_idx')],
            },
        ),
    ]
