# Generated by Django 4.2.11 on 2026-09-29 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0029_seoreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('om', 'Oromo')], default='en', help_text='Target search language code (e.g. "en", "am").', max_length=10),
        ),
        migrations.AlterField(
            model_name='keywordranking',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('om', 'Oromo')], default='en', help_text='Target search language code.', max_length=10),
        ),
        migrations.CreateModel(
            name='KeywordIntelligenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_volume', models.PositiveIntegerField(blank=True, help_text='Estimated average monthly search volume at time of snapshot.', null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated Cost Per Click at time of snapshot.', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency symbol/code for CPC.', max_length=10)),
                ('competition', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Advertiser competition level.', max_length=20, null=True)),
                ('competition_index', models.FloatField(blank=True, help_text='Relative competition index (0.0 - 1.0).', null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='Organic keyword difficulty score (0-100).', null=True)),
                ('intent', models.CharField(blank=True, choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], help_text='Search intent.', max_length=30, null=True)),
                ('source', models.CharField(default='unconfigured', help_text='Provider data source.', max_length=50)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the snapshot was recorded.')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Raw snapshot data.')),
                ('keyword', models.ForeignKey(help_text='The keyword this snapshot measurement belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_snapshots', to='seo.keyword')),
            ],
            options={
                'verbose_name': 'keyword intelligence snapshot',
                'verbose_name_plural': 'keyword intelligence snapshots',
                'db_table': 'seo_keyword_intelligence_snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['keyword', '-recorded_at'], name='kw_intel_snap_kw_rec_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_volume', models.PositiveIntegerField(blank=True, help_text='Estimated average monthly search volume in target country/language.', null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated average Cost Per Click in target country/currency.', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency symbol/code for CPC (e.g. USD, ETB).', max_length=10)),
                ('competition', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Categorical advertiser competition level (Low, Medium, High).', max_length=20, null=True)),
                ('competition_index', models.FloatField(blank=True, help_text='Relative competition index score between 0.0 and 1.0.', null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='Organic SEO difficulty estimate between 0 and 100.', null=True)),
                ('intent', models.CharField(blank=True, choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], help_text='Deterministic or provider-sourced search intent classification.', max_length=30, null=True)),
                ('source', models.CharField(default='unconfigured', help_text='Provider or source mechanism (e.g. dataforseo, mock, internal, unconfigured).', max_length=50)),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('STALE', 'Stale'), ('REFRESHING', 'Refreshing'), ('UNAVAILABLE', 'Unavailable'), ('ERROR', 'Error')], db_index=True, default='UNAVAILABLE', help_text='Data freshness and availability status.', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message from the last provider call, if any.')),
                ('last_refreshed_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent successful or attempted intelligence refresh.', null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Raw metadata, provider attributes, and breakdown numbers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.OneToOneField(help_text='The tracked keyword these metrics belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='seo.keyword')),
            ],
            options={
                'verbose_name': 'keyword intelligence',
                'verbose_name_plural': 'keyword intelligence',
                'db_table': 'seo_keyword_intelligence',
                'indexes': [models.Index(fields=['status', '-last_refreshed_at'], name='kw_intel_status_idx')],
            },
        ),
    ]
